#!/usr/bin/env bash
#
# Switches this service between the local and production environments in one
# command, so nothing about a developer's laptop leaks into a deployed run.
#
#   ./scripts/use-env.sh local        # SQLite-free local Postgres, disk storage, open registration
#   ./scripts/use-env.sh production   # RDS-side Postgres role, S3 storage, registration closed
#
# Secrets are never written by this script from thin air: production values are
# read from .env.production.local (gitignored, created once on the host). If a
# required value is missing the script stops rather than starting a service with
# a default secret.
set -euo pipefail

cd "$(dirname "$0")/.."

MODE="${1:-}"
if [[ "$MODE" != "local" && "$MODE" != "production" ]]; then
  echo "usage: $0 {local|production}" >&2
  exit 64
fi

# Never clobber an existing .env silently — it is the only copy of the running config.
if [[ -f .env ]]; then
  cp .env ".env.backup.$(date +%Y%m%d%H%M%S)"
fi

random_secret() { openssl rand -base64 48 | tr -d '\n'; }

if [[ "$MODE" == "local" ]]; then
  # Reuse an existing local secret so sessions survive a switch back and forth.
  SECRET="$(grep -E '^SESSION_SECRET=' .env 2>/dev/null | cut -d= -f2- | tr -d '"' || true)"
  [[ -n "$SECRET" ]] || SECRET="$(random_secret)"

  # Resolved here, not written as a ${...} expression: .env is read by a plain
  # parser (src/lib/loadEnv.ts), not by a shell, so it performs no expansion.
  # Defaults match the repo's docker-compose.yml; export DATABASE_URL to override.
  LOCAL_DB="${DATABASE_URL:-postgresql://hotelcrm:dev_password@localhost:5432/version_control_dev?schema=public}"

  cat > .env <<EOF
# Generated by scripts/use-env.sh local — $(date -u +%Y-%m-%dT%H:%M:%SZ)
NODE_ENV=development
PORT=3002
ADMIN_PATH=/version-control
INSTALL_PATH=/install

# Left blank on purpose: the server falls back to the machine's LAN address so a
# phone on the same Wi-Fi can open the generated links. iOS OTA install will not
# work locally (it requires real HTTPS) — the Android path is testable.
PUBLIC_BASE_URL=

DATABASE_URL="$LOCAL_DB"
SESSION_SECRET="$SECRET"

STORAGE_DRIVER=local
STORAGE_ROOT=./storage
AWS_REGION=eu-central-1

ALLOW_REGISTRATION=1
REGISTRATION_INVITE_CODE=

MAX_UPLOAD_BYTES=1073741824
EOF

  echo "→ .env set to LOCAL"
  echo "   admin   http://localhost:3002/version-control"
  echo "   install http://localhost:3002/install"
  echo
  echo "   Next: docker compose up -d postgres && npm run prisma:migrate && npm run dev"
  exit 0
fi

# ── production ────────────────────────────────────────────────────────────────

SECRETS_FILE=".env.production.local"
if [[ ! -f "$SECRETS_FILE" ]]; then
  cat >&2 <<EOF
Missing $SECRETS_FILE.

Create it once on the host (it is gitignored and never leaves the box):

  cat > $SECRETS_FILE <<'SECRETS'
  PUBLIC_BASE_URL=https://hotelcrm.app
  DATABASE_URL=postgresql://hotelcrm_vc:<db-password>@localhost:5432/hotelcrm_dev?schema=version_control
  SESSION_SECRET=$(random_secret)
  SECRETS

The database role and password come from scripts/provision-db.sql.
EOF
  exit 1
fi

# shellcheck disable=SC1090
set -a; source "$SECRETS_FILE"; set +a

fail=0
for var in PUBLIC_BASE_URL DATABASE_URL SESSION_SECRET; do
  if [[ -z "${!var:-}" ]]; then
    echo "error: $var is empty in $SECRETS_FILE" >&2
    fail=1
  fi
done
[[ "$PUBLIC_BASE_URL" == https://* ]] || {
  echo "error: PUBLIC_BASE_URL must be https — iOS refuses plain http for OTA installs" >&2
  fail=1
}
# A short secret is a weak secret; 32 chars is the floor for the session signing key.
(( ${#SESSION_SECRET} >= 32 )) || {
  echo "error: SESSION_SECRET must be at least 32 characters" >&2
  fail=1
}
[[ $fail -eq 0 ]] || exit 1

cat > .env <<EOF
# Generated by scripts/use-env.sh production — $(date -u +%Y-%m-%dT%H:%M:%SZ)
NODE_ENV=production
PORT=3002
ADMIN_PATH=/version-control
INSTALL_PATH=/install

PUBLIC_BASE_URL=$PUBLIC_BASE_URL
DATABASE_URL="$DATABASE_URL"
SESSION_SECRET="$SESSION_SECRET"

STORAGE_DRIVER=s3
S3_BUCKET=${S3_BUCKET:-hotelcrm-uploads}
S3_PREFIX=${S3_PREFIX:-app-builds}
AWS_REGION=${AWS_REGION:-eu-central-1}
STORAGE_ROOT=/var/lib/hotel-crm-version-control

# Closed: operators are created with \`npm run user:create\`.
ALLOW_REGISTRATION=0
REGISTRATION_INVITE_CODE=

MAX_UPLOAD_BYTES=1073741824
EOF

chmod 600 .env

echo "→ .env set to PRODUCTION"
echo "   admin   $PUBLIC_BASE_URL/version-control"
echo "   install $PUBLIC_BASE_URL/install"
echo
echo "   AWS credentials are NOT written here — they come from the EC2 instance"
echo "   role or the IAM user configured on the host."
echo
echo "   Next: npm ci --omit=dev && npm run prisma:deploy && npm run build && pm2 reload hotel-crm-version-control"
