import { readFileSync } from 'node:fs';
import path from 'node:path';

/**
 * Pins the documented APNs topics to the mobile apps' real bundle IDs.
 *
 * The `apns-topic` header must equal the bundle identifier of the app that
 * minted the device token. APNs answers a mismatch with `400 BadTopic`, and
 * nothing else in the system can detect that the value is wrong: the worker
 * boots, logs "APNs configured for {worker: configured, checker: configured}"
 * because both variables are merely *present*, and then fails every single
 * send.
 *
 * That is not hypothetical. `.env.example` shipped
 * `APNS_BUNDLE_ID_WORKER=com.hotelcrm.workerapp` /
 * `APNS_BUNDLE_ID_CHECKER=com.hotelcrm.checkerapp` — plausible-looking
 * placeholders that were copied verbatim into the deployed `.env` and never
 * corrected, while the apps actually ship as `com.fhmhotelservices.*`. The
 * result was a 100% iOS push outage across BOTH apps, for as long as those
 * values stood, presenting as a healthy worker that steadily dead-lettered
 * notifications.
 *
 * This is the backend counterpart to
 * `mobile/checker-app/src/__tests__/android-fcm-config.test.ts`, which pins
 * the Android/FCM half of the same wiring. Android had a guard; iOS did not,
 * which is precisely why this defect survived on the iOS side only.
 *
 * Asserted against `app.json` because that is the single input the iOS build
 * reads for the bundle identifier — `ios/` is generated by prebuild and
 * gitignored, so it is not a source of truth.
 *
 * A test cannot see the deployed `.env` (untracked, and not present in CI),
 * so this guards the value operators copy FROM. The runtime half of the
 * defense is `PushConfigurationError` (push-provider.ts), which turns a
 * topic rejection into a single ERROR log naming the topic instead of a
 * silent slide into DEAD_LETTER.
 */
describe('APNs topic configuration', () => {
  const repoRoot = path.resolve(process.cwd(), '..');

  const bundleIdOf = (app: 'worker-app' | 'checker-app' | 'manager-app'): string => {
    const appJson = JSON.parse(
      readFileSync(path.join(repoRoot, 'mobile', app, 'app.json'), 'utf8')
    );
    return appJson.expo.ios.bundleIdentifier;
  };

  const envExample = (): Map<string, string> => {
    const text = readFileSync(path.join(process.cwd(), '.env.example'), 'utf8');
    const entries = new Map<string, string>();
    for (const line of text.split('\n')) {
      const match = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
      if (match) entries.set(match[1], match[2]);
    }
    return entries;
  };

  it('.env.example documents the worker app’s real bundle identifier', () => {
    expect(envExample().get('APNS_BUNDLE_ID_WORKER')).toBe(bundleIdOf('worker-app'));
  });

  it('.env.example documents the checker app’s real bundle identifier', () => {
    expect(envExample().get('APNS_BUNDLE_ID_CHECKER')).toBe(bundleIdOf('checker-app'));
  });

  // Added 2026-09-22 with mobile/manager-app. The manager topic shipped in
  // .env.example one commit before the app existed, which is exactly the
  // window in which an unpinned placeholder gets copied into a deployed .env
  // and causes a silent 100% push outage -- the defect this whole file exists
  // to prevent. Closed as soon as there was an app.json to assert against.
  it('.env.example documents the manager app’s real bundle identifier', () => {
    expect(envExample().get('APNS_BUNDLE_ID_MANAGER')).toBe(bundleIdOf('manager-app'));
  });

  it('the apps have distinct bundle identifiers', () => {
    // A copy-paste between the two app.json files would make both topics
    // identical, and the resulting failure is asymmetric and confusing: one
    // app keeps working while the other gets DeviceTokenNotForTopic on every
    // send. PushApp exists precisely to keep these two apart (PR 7.8).
    const ids = [bundleIdOf('worker-app'), bundleIdOf('checker-app'), bundleIdOf('manager-app')];
    expect(new Set(ids).size).toBe(ids.length);
  });

  /**
   * The boot summary must cover EVERY app, not a hand-written subset.
   *
   * It listed `worker` and `checker` only, from before MANAGER existed
   * (2026-09-22) until 2026-09-23. A production host with
   * `APNS_BUNDLE_ID_MANAGER` correctly set still logged a two-app summary, so
   * a configured manager topic and an unconfigured one looked identical in the
   * boot log — the exact thing that line exists to make visible. Found by
   * setting the variable on the live host and not believing the log.
   */
  it('the APNs boot summary is derived from the enum, not hand-listed', () => {
    const src = readFileSync(
      path.join(__dirname, '..', 'modules', 'notifications', 'outbox-transport.ts'),
      'utf8'
    );
    const summary = src.slice(src.indexOf("'PUSH transport: APNs configured for'"));
    const body = summary.slice(0, summary.indexOf('fcmClient'));

    // Enum-driven: adding a PushApp member extends the log automatically.
    expect(body).toContain('Object.values(PushApp)');
    // And NOT a literal list, which is how it fell behind the enum before.
    expect(body).not.toMatch(/worker:\s*apnsTopics\[PushApp\.WORKER\]/);
    expect(body).not.toMatch(/checker:\s*apnsTopics\[PushApp\.CHECKER\]/);
  });

  it('does not carry the placeholder values that caused the outage', () => {
    // Named explicitly rather than left to the equality assertions above: if
    // someone later changes app.json to match a placeholder instead of the
    // other way round, the equality checks would pass and the outage would
    // return.
    const entries = envExample();
    expect(entries.get('APNS_BUNDLE_ID_WORKER')).not.toBe('com.hotelcrm.workerapp');
    expect(entries.get('APNS_BUNDLE_ID_CHECKER')).not.toBe('com.hotelcrm.checkerapp');
  });
});
