import { readFileSync } from 'node:fs';
import path from 'node:path';

/**
 * Pins the documented APNs topics to the mobile apps' real bundle IDs.
 *
 * The `apns-topic` header must equal the bundle identifier of the app that
 * minted the device token. APNs answers a mismatch with `400 BadTopic`, and
 * nothing else in the system can detect that the value is wrong: the worker
 * boots, logs "APNs configured for {worker: configured, checker: configured}"
 * because both variables are merely *present*, and then fails every single
 * send.
 *
 * That is not hypothetical. `.env.example` shipped
 * `APNS_BUNDLE_ID_WORKER=com.hotelcrm.workerapp` /
 * `APNS_BUNDLE_ID_CHECKER=com.hotelcrm.checkerapp` — plausible-looking
 * placeholders that were copied verbatim into the deployed `.env` and never
 * corrected, while the apps actually ship as `com.fhmhotelservices.*`. The
 * result was a 100% iOS push outage across BOTH apps, for as long as those
 * values stood, presenting as a healthy worker that steadily dead-lettered
 * notifications.
 *
 * This is the backend counterpart to
 * `mobile/checker-app/src/__tests__/android-fcm-config.test.ts`, which pins
 * the Android/FCM half of the same wiring. Android had a guard; iOS did not,
 * which is precisely why this defect survived on the iOS side only.
 *
 * Asserted against `app.json` because that is the single input the iOS build
 * reads for the bundle identifier — `ios/` is generated by prebuild and
 * gitignored, so it is not a source of truth.
 *
 * A test cannot see the deployed `.env` (untracked, and not present in CI),
 * so this guards the value operators copy FROM. The runtime half of the
 * defense is `PushConfigurationError` (push-provider.ts), which turns a
 * topic rejection into a single ERROR log naming the topic instead of a
 * silent slide into DEAD_LETTER.
 */
describe('APNs topic configuration', () => {
  const repoRoot = path.resolve(process.cwd(), '..');

  const bundleIdOf = (app: 'worker-app' | 'checker-app'): string => {
    const appJson = JSON.parse(
      readFileSync(path.join(repoRoot, 'mobile', app, 'app.json'), 'utf8')
    );
    return appJson.expo.ios.bundleIdentifier;
  };

  const envExample = (): Map<string, string> => {
    const text = readFileSync(path.join(process.cwd(), '.env.example'), 'utf8');
    const entries = new Map<string, string>();
    for (const line of text.split('\n')) {
      const match = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
      if (match) entries.set(match[1], match[2]);
    }
    return entries;
  };

  it('.env.example documents the worker app’s real bundle identifier', () => {
    expect(envExample().get('APNS_BUNDLE_ID_WORKER')).toBe(bundleIdOf('worker-app'));
  });

  it('.env.example documents the checker app’s real bundle identifier', () => {
    expect(envExample().get('APNS_BUNDLE_ID_CHECKER')).toBe(bundleIdOf('checker-app'));
  });

  it('the two apps have distinct bundle identifiers', () => {
    // A copy-paste between the two app.json files would make both topics
    // identical, and the resulting failure is asymmetric and confusing: one
    // app keeps working while the other gets DeviceTokenNotForTopic on every
    // send. PushApp exists precisely to keep these two apart (PR 7.8).
    expect(bundleIdOf('worker-app')).not.toBe(bundleIdOf('checker-app'));
  });

  it('does not carry the placeholder values that caused the outage', () => {
    // Named explicitly rather than left to the equality assertions above: if
    // someone later changes app.json to match a placeholder instead of the
    // other way round, the equality checks would pass and the outage would
    // return.
    const entries = envExample();
    expect(entries.get('APNS_BUNDLE_ID_WORKER')).not.toBe('com.hotelcrm.workerapp');
    expect(entries.get('APNS_BUNDLE_ID_CHECKER')).not.toBe('com.hotelcrm.checkerapp');
  });
});
