import { readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * The Android FCM config must actually describe THIS app.
 *
 * `google-services.json` is processed at build time by the Google Services
 * Gradle plugin, which looks for the client whose `package_name` equals the
 * app's `applicationId`. No match is a build failure; a match whose
 * `mobilesdk_app_id` belongs to a DIFFERENT registration is worse, because it
 * builds and then fails at runtime when the device tries to register for a
 * token — which surfaces only as "recipient has no registered devices" in the
 * Platform Worker log, long after anyone is looking.
 *
 * WHY THIS FILE EXISTS. On 2026-09-23 the Firebase project was found to hold
 * its worker and checker Android apps under `com.hotelcrm.*` — the placeholder
 * namespace that had already caused one APNs outage — while the committed
 * configs claimed `com.fhmhotelservices.*`. Commit `3e425c0e` had hand-edited
 * the package names in the JSON instead of re-registering the apps, so the
 * file and Firebase disagreed, and **not one Android device had ever
 * registered a push token for any of the three apps.**
 *
 * The manager app's entry was generated by the Firebase API against its real
 * package and is committed UNEDITED. That is the rule this test enforces: the
 * config is an artifact to regenerate, never a file to correct by hand.
 */
describe('Android FCM configuration', () => {
  const appDir = join(__dirname, '..', '..');

  const appJson = JSON.parse(readFileSync(join(appDir, 'app.json'), 'utf8')) as {
    expo: { android?: { package?: string; googleServicesFile?: string } };
  };
  const config = JSON.parse(readFileSync(join(appDir, 'google-services.json'), 'utf8')) as {
    project_info: { project_id: string };
    client: {
      client_info: { mobilesdk_app_id: string; android_client_info: { package_name: string } };
      api_key?: { current_key: string }[];
    }[];
  };

  it('app.json points at the config, as the other two apps do', () => {
    expect(appJson.expo.android?.googleServicesFile).toBe('./google-services.json');
  });

  it('the config contains a client for this app’s exact package', () => {
    const pkg = appJson.expo.android?.package;
    expect(pkg).toBe('com.fhmhotelservices.managerapp');

    const mine = config.client.find((c) => c.client_info.android_client_info.package_name === pkg);
    // The assertion that matters: no match means the Gradle plugin fails the
    // build with "No matching client found for package name".
    expect(mine).toBeDefined();
    expect(mine!.client_info.mobilesdk_app_id).toMatch(/^1:\d+:android:[0-9a-f]+$/);
    expect(mine!.api_key?.[0]?.current_key).toBeTruthy();
  });

  it('is the project this backend sends through', () => {
    // A config from a different Firebase project would mint tokens the
    // Platform Worker's credentials cannot send to — MISMATCH_SENDER_ID, per
    // device, invisible server-side until a delivery is attempted.
    expect(config.project_info.project_id).toBe('fhm-hotelservice');
  });

  it('the manager client is not a hand-edited copy of another app’s', () => {
    const ids = config.client.map((c) => c.client_info.mobilesdk_app_id);
    // Every registration in the file is distinct. Two clients sharing an
    // app id is the signature of a package name edited by hand — exactly what
    // happened to worker and checker.
    expect(new Set(ids).size).toBe(ids.length);
  });
});
